### PR TITLE
N 7.0

### PR DESCRIPTION
**Pull request by farfromrefug**
* build the component as esm
* clean up some code like `console.log` or `Trace.enable()`
* starting the migration of demo apps to 7.0. But for now i finished it only for the vue demo
* added svelte support
* renamed to @nativescript-community/ui-pager
* published first alpha https://www.npmjs.com/package/@nativescript-community/ui-pager

### CODE REVIEW

**Comment by limux82** [comment]
I have tried the version of @nativescript-community/ui-pager 13.0.0-alpha.5  and I have problem in import the PagerModule from @nativescript-community/ui-pager/angular. I think the package is not compiled correctly. Checking in node-modules @nativescript-community/ui-pager/angular folder contains only the package.json file. 

The angular module is not exported
ERROR in src/app/shared/shared.module.ts:33:29 - error TS2307: Cannot find module '@nativescript-community/ui-pager/angular' or its corresponding type declarations.
33 import { PagerModule } from '@nativescript-community/ui-pager/angular';

**Comment by farfromrefug** [comment]
@limux82 indeed I did not finished the angular part of it. Need to do that

**Comment by alexlnos** [comment]
Hi there is an error like this
vue
@nativescript-community/ui-pager 13.0.0-alpha.5
Maybe I'm doing something wrong?
I put it on a newly created project.


`CONSOLE LOG: TypeError: Could not load view for: nativepager. ReferenceError: NativeClass is not defined ReferenceError: NativeClass is not defined
at Module.../node_modules/@nativescript-community/ui-pager/pager.js (file: node_modules/@nativescript-community/ui-pager/pager.ios.js:656:4)
at __webpack_require__ (file: app/webpack/bootstrap:816:0)
at fn (file: app/webpack/bootstrap:120:0)
at Object.resolver (file: node_modules/@nativescript-community/ui-pager/vue/index.js:2:42)
at getViewClass (file: node_modules/nativescript-vue/dist/index.js:7666:17)
at new ElementNode (file: node_modules/nativescript-vue/dist/index.js:8479:20)
at Function.createElement (file: node_modules/nativescript-vue/dist/index.js:8591:13)
at Object.createElement$1 [as createElement] (file: node_modules/nativescript-vue/dist/index.js:8620:22)
at createElm (file: node_modules/nativescript-vue/dist/index.js:5291:18)
at VueComponent.patch [as __patch__] (file: node_modules/nativescript-vue/dist/index.js:5819:6)
CONSOLE LOG: TypeError: Class constructor View cannot be invoked without 'new'`

**Comment by farfromrefug** [comment]
My bad will fix this in a few hours

**Comment by farfromrefug** [comment]
@alexlnos  @limux82 published 13.0.0-alpha.6 which should fix both your issues for N 7.0

**Comment by alexlnos** [comment]
Hello! I can't migrate my application to NS7, there was a problem with this module
Maybe I'm doing something wrong?
To make sure that my application is not to blame, I installed the module on the newly created project.
When I build my application I get this error

`CONSOLE LOG: TypeError: Could not load view for: nativepager. ReferenceError: NativeClass is not defined ReferenceError: NativeClass is not defined
at Module.../node_modules/@nativescript-community/ui-pager/pager.js (file: node_modules/@nativescript-community/ui-pager/pager.ios.js:656:4)
at __webpack_require__ (file: app/webpack/bootstrap:816:0)
at fn (file: app/webpack/bootstrap:120:0)
at Object.resolver (file: node_modules/@nativescript-community/ui-pager/vue/index.js:2:42)
at getViewClass (file: node_modules/nativescript-vue/dist/index.js:7666:17)
at new ElementNode (file: node_modules/nativescript-vue/dist/index.js:8479:20)
at Function.createElement (file: node_modules/nativescript-vue/dist/index.js:8591:13)
at Object.createElement$1 [as createElement] (file: node_modules/nativescript-vue/dist/index.js:8620:22)
at createElm (file: node_modules/nativescript-vue/dist/index.js:5291:18)
at VueComponent.patch [as __patch__] (file: node_modules/nativescript-vue/dist/index.js:5819:6)
`

**Comment by farfromrefug** [comment]
@alexlnos what version of the plugin are you using?

**Comment by alexlnos** [comment]
on friday i tested 13.0.0-alpha.5, today same thing on 13.0.0-alpha.6

**Comment by farfromrefug** [comment]
@alexlnos ok i did something wrong i ll check

**Comment by farfromrefug** [comment]
@alexlnos this time it should be good with 13.0.0-alpha.7

**Comment by triniwiz** [comment]
@farfromrefug ready to merge ?

**Comment by farfromrefug** [comment]
@triniwiz waiting for @alexlnos to confirm it works

**Comment by keerl** [comment]
Does this have Angular 10 support yet? I am trying out this RC with my project and I am getting the following error.

```
ERROR in ../node_modules/@nativescript-community/ui-pager/angular/fesm2015/nativescript-community-ui-pager-angular.js
Module not found: Error: Can't resolve '@nativescript/angular/element-registry' in '/Users/karlschmaltz/Desktop/Projects/test-app/node_modules/@nativescript-community/ui-pager/angular/fesm2015'
 @ ../node_modules/@nativescript-community/ui-pager/angular/fesm2015/nativescript-community-ui-pager-angular.js 5:0-112 10:0-15 11:0-15 250:48-70 271:77-90
 @ ./app/app.module.ts
 @ ./main.ts
```

Same error I'm getting on this plugin as well https://github.com/nativescript-community/ui-image/issues/31

**Comment by farfromrefug** [comment]
@NathanWalker do you know why we get that error with @nativescript/angular. I am getting a lot of reports like that.
The typings for element-registry exists in @nativescript/angular. But pacakges.json "module" and "main" points to directories where element-registry does not exist.

**Comment by romandragan** [comment]
With alpha 7 I'm getting `TypeError: Class constructor ContainerView cannot be invoked without 'new'` when trying to use Pager in NativeScript-Vue project.

The same code worked before migrating to NS 7.

**Comment by farfromrefug** [comment]
@romandragan what version are you using ? This is because you use non compatible code (between the plugin and N7)

**Comment by romandragan** [comment]
@farfromrefug, @nativescript-community/ui-pager 13.0.0-alpha.7.

**Comment by farfromrefug** [comment]
@romandragan it feels like you are still using N 6.x. Can you share your package.json? Or maybeeven your project?

**Comment by keerl** [comment]
@farfromrefug Are the Angular import errors I am getting as easy to fix as it was in `ui-image`? Just wondering if that is going to be addressed. https://github.com/nativescript-community/ui-image/issues/31

**Comment by farfromrefug** [comment]
@keerl yes and no. already fixed 2 of them but dont know where to get`InvisibleNode`. @NathanWalker ?

**Comment by mapo80** [comment]
Hi I've created a pull request to solve this:

https://github.com/triniwiz/nativescript-pager/issues/185

Pull request is: https://github.com/farfromrefug/nativescript-pager/pull/1

**Comment by keerl** [comment]
@farfromrefug could you publish an updated version to NPM so I can test?

**Comment by farfromrefug** [comment]
@keerl actually had to try a different fix as i had tsc issues. released 13.0.0-alpha.8. Can you try?

**Comment by keerl** [comment]
My project now runs, but when I go to a page with the Pager I get this error on Android and iOS (same as @romandragan above). Using latest @nativescript/core and CLI.

```
ERROR Error: Uncaught (in promise): TypeError: Class constructor ContainerView cannot be invoked without 'new'
JS: TypeError: Class constructor ContainerView cannot be invoked without 'new'
JS:     at new PagerBase (file: node_modules/@nativescript-community/ui-pager/pager.common.js:54:0)
JS:     at new Pager (file: node_modules/@nativescript-community/ui-pager/pager.android.js:22:0)
JS:     at ViewUtil.createView (file: node_modules/@nativescript/angular/fesm2015/nativescript-angular.js:2543:0)
JS:     at EmulatedRenderer.createElement (file: node_modules/@nativescript/angular/fesm2015/nativescript-angular.js:2745:0)
JS:     at EmulatedRenderer.createElement (file: node_modules/@nativescript/angular/fesm2015/nativescript-angular.js:2962:0)
JS:     at elementCreate (file: node_modules/@angular/core/fesm2015/core.js:6982:0)
JS:     at Module.ɵɵelementStart (file: node_modules/@angular/core/fesm2015/core.js:13876:0)
```

**Comment by farfromrefug** [comment]
@keerl can you share your package.json?

**Comment by keerl** [comment]
@farfromrefug yep. This is from a big project so there's a lot of stuff.

```
{
    "description": "NativeScript Application",
    "repository": "https://github.com/keerl/xxx",
    "license": "SEE LICENSE IN <your-license-filename>",
    "scripts": {
        "clean": "npx rimraf hooks node_modules package-lock.json platforms",
        "format": "eslint '**/*.{ts,json}' --quiet --fix && npx stylelint '**/*.scss' --fix && prettier --write **/*.html",
        "postinstall": "npm run ngcc",
        "lint": "eslint '**/*.{ts,json}' --quiet && npx stylelint '**/*.scss' && prettier --check **/*.html",
        "ngcc": "ngcc --properties es2015 module main --first-only"
    },
    "dependencies": {
        "@angular/animations": "~10.0.0",
        "@angular/common": "~10.0.0",
        "@angular/compiler": "~10.0.0",
        "@angular/core": "~10.0.0",
        "@angular/forms": "~10.0.0",
        "@angular/platform-browser": "~10.0.0",
        "@angular/platform-browser-dynamic": "~10.0.0",
        "@angular/router": "~10.0.0",
        "@nativescript-community/ui-image": "latest",
        "@nativescript-community/ui-material-bottomnavigationbar": "latest",
        "@nativescript-community/ui-material-button": "latest",
        "@nativescript-community/ui-material-cardview": "latest",
        "@nativescript-community/ui-material-dialogs": "latest",
        "@nativescript-community/ui-material-ripple": "latest",
        "@nativescript-community/ui-material-snackbar": "latest",
        "@nativescript-community/ui-pager": "latest",
        "@nativescript/angular": "10.0.0",
        "@nativescript/appsync": "latest",
        "@nativescript/appversion": "latest",
        "@nativescript/camera": "latest",
        "@nativescript/core": "latest",
        "@nativescript/directions": "latest",
        "@nativescript/email": "latest",
        "@nativescript/firebase": "rc",
        "@nativescript/geolocation": "~7.0.0",
        "@nativescript/hook": "~2.0.0",
        "@nativescript/imagepicker": "latest",
        "@nativescript/iqkeyboardmanager": "~2.0.0",
        "@nativescript/theme": "~2.3.0",
        "@nstudio/nativescript-cardview": "latest",
        "@nstudio/nativescript-mapbox": "^6.0.0-rc.0",
        "core-js": "^2.6.9",
        "nativescript-algolia": "^1.2.2",
        "nativescript-bitmap-factory": "^1.8.1",
        "nativescript-clipboard": "^1.2.0",
        "nativescript-filter-select": "^1.3.0",
        "nativescript-phone": "^2.0.0",
        "nativescript-theme-core": "^1.0.4",
        "nativescript-ui-listview": "9.0.2",
        "nativescript-ui-sidedrawer": "9.0.3",
        "reflect-metadata": "~0.1.12",
        "rxjs": "^6.5.0",
        "zone.js": "0.11.1"
    },
    "devDependencies": {
        "@angular/compiler-cli": "~10.0.0",
        "@nativescript/android": "7.0.0",
        "@nativescript/ios": "7.0.0",
        "@nativescript/types": "~7.0.0",
        "@nativescript/webpack": "~3.0.0",
        "@ngtools/webpack": "~10.0.0",
        "@typescript-eslint/eslint-plugin": "^4.1.0",
        "@typescript-eslint/parser": "^4.1.0",
        "eslint": "^7.9.0",
        "eslint-config-prettier": "^6.11.0",
        "eslint-plugin-prettier": "^3.1.4",
        "eslint-plugin-tsdoc": "^0.2.7",
        "jest": "^26.4.2",
        "jest-circus": "^26.4.2",
        "jest-cli": "^26.4.2",
        "prettier": "^2.1.1",
        "sass": "^1.26.10",
        "stylelint": "^13.7.1",
        "stylelint-config-sass-guidelines": "^7.1.0",
        "typescript": "~3.9.0"
    },
    "readme": "NativeScript Application",
    "main": "main.js"
}
```

**Comment by farfromrefug** [comment]
@keel i think something is wrong with your setup. Can you share your `tsconfig.json`?

**Comment by keerl** [comment]
@farfromrefug yep.

```
{
    "compilerOptions": {
        "module": "ESNext",
        "target": "ES2017",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "skipLibCheck": true,
        "lib": ["es2018", "es2017", "dom", "es6"],
        "baseUrl": ".",
        "paths": {
            "~/*": ["app/*"]
        }
    },
    "include": ["src/tests/**/*.ts", "src/**/*.ios.ts", "src/**/*.android.ts"],
    "files": ["./references.d.ts", "./src/main.ts"],
    "exclude": ["node_modules", "platforms", "e2e"]
}
```

**Comment by farfromrefug** [comment]
OK all good. Really weird. So you understand it means the pager comp and nativescript core are not in the same "target". One is using Es2017 syntax. The other one is using es5 syntax. 
So as you are using " latest" in your package.json we are not sure what version is actually installed. You need to go in the node_modules both for the pager plugin and the core. Look at their package.json and give me the version for both.

**Comment by keerl** [comment]
**@nativescript-community/ui-pager**: "version": "13.0.0-alpha.8"

**@nativescript/core**: "version": "7.0.3"

**Comment by farfromrefug** [comment]
Ok all good :s I am sorry I need to think and test things here. Won't be able to do it before tomorrow

**Comment by keerl** [comment]
Thanks. I made a sample project which should be easier for debugging. It's a blank Angular 10 NS7 project with only ui-pager added, gets the same error.
[ui-pager-issue.zip](https://github.com/triniwiz/nativescript-pager/files/5242112/ui-pager-issue.zip)

**Comment by farfromrefug** [comment]
@keerl fixed in latest alpha! also fixed snapping behavior on ios

**Comment by mapo80** [comment]
Hi @farfromrefug, this fix will be available for previous version of the library?

https://github.com/triniwiz/nativescript-pager/pull/180/commits/fb25e6ac71cc6ccbc7475d976b7b49d3f46e6e7a

**Comment by farfromrefug** [comment]
@mapo80 did not know about that issue. But yes :D

**Comment by mapo80** [comment]
@farfromrefug so we can use fix without upgrading to NS 7?

**Comment by mapo80** [comment]
Backport will be great for devs that will wait to upgrade to NS7. @farfromrefug and @triniwiz

**Comment by keerl** [comment]
Just tested it and everything seems to be working great! Thanks for your hard work @farfromrefug!

**Comment by farfromrefug** [comment]
@triniwiz any feedback on this? Trying to get a hold of you on slack.

**Comment by triniwiz** [comment]
Thank you 😎

**Pull request merged**
